// textures
#define BACKICON		"Editor/BackIcon.png"
#define CAMERAICON		"Editor/CameraIcon.png"
#define DEFULTFILEICON	"Editor/DefaultFileIcon.png"
#define FOLDERICON		"Editor/FolderIcon.png"
#define IMAGEFILEICON	"Editor/ImageFileIcon.png"
#define NOTEXTUREICON	"Editor/NoTextureIcon.png"
#define PLAYBUTTON		"Editor/PlayButton.png"
#define SCENEFILEICON	"Editor/SceneFileIcon.png"
#define SHADERFILEICON	"Editor/ShaderFileIcon.png"
#define STOPBUTTON		"Editor/StopButton.png"
