#pragma once

// mouse
#define MOUSE_LBUTTON 0x01
#define MOUSE_RBUTTON 0x02
#define MOUSE_MBUTTON 0x04
#define MOUSE_XBUTTON1 0x05
#define MOUSE_XBUTTON2 0x06

// keyboard 
#define KEYCODE_UNKNOWN -1

#define KEYCODE_0 0x30 
#define KEYCODE_1 0x31 
#define KEYCODE_2 0x32 
#define KEYCODE_3 0x33 
#define KEYCODE_4 0x34 
#define KEYCODE_5 0x35 
#define KEYCODE_6 0x36 
#define KEYCODE_7 0x37 
#define KEYCODE_8 0x38 
#define KEYCODE_9 0x39 

#define KEYCODE_NUM_LOCK 0x90
#define KEYCODE_NUM_0 0x60
#define KEYCODE_NUM_1 0x61 
#define KEYCODE_NUM_2 0x62 
#define KEYCODE_NUM_3 0x63 
#define KEYCODE_NUM_4 0x64 
#define KEYCODE_NUM_5 0x65 
#define KEYCODE_NUM_6 0x66 
#define KEYCODE_NUM_7 0x67 
#define KEYCODE_NUM_8 0x68 
#define KEYCODE_NUM_9 0x69 
#define KEYCODE_NUM_DECIMAL 0x6E
#define KEYCODE_NUM_DIVIDE 0x6F
#define KEYCODE_NUM_MULTIPLY 0x6A
#define KEYCODE_NUM_SUBTRACT 0x6D
#define KEYCODE_NUM_ADD 0x6B
#define KEYCODE_NUM_ENTER 0x0D

#define KEYCODE_A 0x41
#define KEYCODE_B 0x42
#define KEYCODE_C 0x43
#define KEYCODE_D 0x44
#define KEYCODE_E 0x45
#define KEYCODE_F 0x46
#define KEYCODE_G 0x47
#define KEYCODE_H 0x48
#define KEYCODE_I 0x49
#define KEYCODE_J 0x4A
#define KEYCODE_K 0x4B
#define KEYCODE_L 0x4C
#define KEYCODE_M 0x4D
#define KEYCODE_N 0x4E
#define KEYCODE_O 0x4F
#define KEYCODE_P 0x50
#define KEYCODE_Q 0x51
#define KEYCODE_R 0x52
#define KEYCODE_S 0x53
#define KEYCODE_T 0x54
#define KEYCODE_U 0x55
#define KEYCODE_V 0x56
#define KEYCODE_W 0x57
#define KEYCODE_X 0x58
#define KEYCODE_Y 0x59
#define KEYCODE_Z 0x5A

#define KEYCODE_MINUS 0xBD
#define KEYCODE_PERIOD 0xBE
#define KEYCODE_LEFT_BRACKET 0xDB
#define KEYCODE_RIGHT_BRACKET 0xDD
#define KEYCODE_SEMICOLON 0xBA 
#define KEYCODE_BACKSLASH 0xDC
#define KEYCODE_FORWORDSLASH 0xBF
#define KEYCODE_SLASH 0xBF
#define KEYCODE_QUOTE 0xDE
#define KEYCODE_APOSTROPHE 0xDE
#define KEYCODE_GRAVE_ACCENT 0xC0
#define KEYCODE_TILDE 0xC0
#define KEYCODE_ESCAPE 0x18
#define KEYCODE_TAB 0x09
#define KEYCODE_BACKSPACE 0x08
#define KEYCODE_SPACE 0x20
#define KEYCODE_ENTER 0x0D
#define KEYCODE_EQUAL 0x3D
#define KEYCODE_COMMA 0xBC

#define KEYCODE_LEFT 0x25
#define KEYCODE_UP 0x26
#define KEYCODE_RIGHT 0x27
#define KEYCODE_DOWN 0x28

#define KEYCODE_INSERT 0x2D
#define KEYCODE_DELETE 0x2E
#define KEYCODE_HOME 0x24
#define KEYCODE_END 0x23
#define KEYCODE_PAGE_UP 0x21
#define KEYCODE_PAGE_DOWN 0x22

#define KEYCODE_CAPS_LOCK 0x14
#define KEYCODE_SELECT 0x29
#define KEYCODE_PRINT 0x2A
#define KEYCODE_EXECUTE 0x2B
#define KEYCODE_HELP 0x2F
#define KEYCODE_PRINT_SCREEN 0x2C
#define KEYCODE_PAUSE 0x13

#define KEYCODE_F1 0x70
#define KEYCODE_F2 0x71
#define KEYCODE_F3 0x72
#define KEYCODE_F4 0x73
#define KEYCODE_F5 0x74
#define KEYCODE_F6 0x75
#define KEYCODE_F7 0x76
#define KEYCODE_F8 0x77
#define KEYCODE_F9 0x78
#define KEYCODE_F10 0x79
#define KEYCODE_F11 0x7A
#define KEYCODE_F12 0x7B
#define KEYCODE_F13 0x7C
#define KEYCODE_F14 0x7D
#define KEYCODE_F15 0x7E
#define KEYCODE_F16 0x7F
#define KEYCODE_F17 0x80
#define KEYCODE_F18 0x81
#define KEYCODE_F19 0x82
#define KEYCODE_F20 0x83
#define KEYCODE_F21 0x84
#define KEYCODE_F22 0x85
#define KEYCODE_F23 0x86
#define KEYCODE_F24 0x87
#define KEYCODE_F25 0x88


#define KEYCODE_SHIFT 0x10
#define KEYCODE_LEFT_SHIFT 0xA0
#define KEYCODE_RIGHT_SHIFT 0xA1

#define KEYCODE_CONTROL 0x11
#define KEYCODE_LEFT_CONTROL 0xA2
#define KEYCODE_RIGHT_CONTROL 0xA3

#define KEYCODE_ALT 0x12
#define KEYCODE_LEFT_ALT 0xA4
#define KEYCODE_RIGHT_ALT 0xA5

#define KEYCODE_LEFT_SUPER 0x5B
#define KEYCODE_RIGHT_SUPER 0x5C

#define KEYCODE_MENU 348
#define KEYCODE_LAST KEYCODE_MENU


namespace Engine
{
	class  KeyCode
	{
	public:
		enum
		{
			UNKNOWN = KEYCODE_UNKNOWN,
			NUM_0 = KEYCODE_0,
			NUM_1 = KEYCODE_1,
			NUM_2 = KEYCODE_2,
			NUM_3 = KEYCODE_3,
			NUM_4 = KEYCODE_4,
			NUM_5 = KEYCODE_5,
			NUM_6 = KEYCODE_6,
			NUM_7 = KEYCODE_7,
			NUM_8 = KEYCODE_8,
			NUM_9 = KEYCODE_9,

			NUMPAD_LOCK = KEYCODE_NUM_LOCK,
			NUMPAD_0 = KEYCODE_NUM_0,
			NUMPAD_1 = KEYCODE_NUM_1,
			NUMPAD_2 = KEYCODE_NUM_2,
			NUMPAD_3 = KEYCODE_NUM_3,
			NUMPAD_4 = KEYCODE_NUM_4,
			NUMPAD_5 = KEYCODE_NUM_5,
			NUMPAD_6 = KEYCODE_NUM_6,
			NUMPAD_7 = KEYCODE_NUM_7,
			NUMPAD_8 = KEYCODE_NUM_8,
			NUMPAD_9 = KEYCODE_NUM_9,
			NUMPAD_DECIMAL = KEYCODE_NUM_DECIMAL,
			NUMPAD_DIVIDE = KEYCODE_NUM_DIVIDE,
			NUMPAD_MULTIPLY = KEYCODE_NUM_MULTIPLY,
			NUMPAD_SUBTRACT = KEYCODE_NUM_SUBTRACT,
			NUMPAD_ADD = KEYCODE_NUM_ADD,
			NUMPAD_ENTER = KEYCODE_NUM_ENTER,

			A = KEYCODE_A,
			B = KEYCODE_B,
			C = KEYCODE_C,
			D = KEYCODE_D,
			E = KEYCODE_E,
			F = KEYCODE_F,
			G = KEYCODE_G,
			H = KEYCODE_H,
			I = KEYCODE_I,
			J = KEYCODE_J,
			K = KEYCODE_K,
			L = KEYCODE_L,
			M = KEYCODE_M,
			N = KEYCODE_N,
			O = KEYCODE_O,
			P = KEYCODE_P,
			Q = KEYCODE_Q,
			R = KEYCODE_R,
			S = KEYCODE_S,
			T = KEYCODE_T,
			U = KEYCODE_U,
			V = KEYCODE_V,
			W = KEYCODE_W,
			X = KEYCODE_X,
			Y = KEYCODE_Y,
			Z = KEYCODE_Z,

			MINUS = KEYCODE_MINUS,
			PERIOD = KEYCODE_PERIOD,
			LEFT_BRACKET = KEYCODE_LEFT_BRACKET,
			RIGHT_BRACKET = KEYCODE_RIGHT_BRACKET,
			SEMICOLON = KEYCODE_SEMICOLON,
			BACKSLASH = KEYCODE_BACKSLASH,
			FORWORDSLASH = KEYCODE_FORWORDSLASH,
			SLASH = KEYCODE_SLASH,
			QUOTE = KEYCODE_QUOTE,
			APOSTROPHE = KEYCODE_APOSTROPHE,
			GRAVE_ACCENT = KEYCODE_GRAVE_ACCENT,
			TILDE = KEYCODE_TILDE,
			ESCAPE = KEYCODE_ESCAPE,
			TAB = KEYCODE_TAB,
			BACKSPACE = KEYCODE_BACKSPACE,
			SPACE = KEYCODE_SPACE,
			ENTER = KEYCODE_ENTER,
			EQUAL = KEYCODE_EQUAL,
			COMMA = KEYCODE_COMMA,

			LEFT = KEYCODE_LEFT,
			UP = KEYCODE_UP,
			RIGHT = KEYCODE_RIGHT,
			DOWN = KEYCODE_DOWN,

			INSERT = KEYCODE_INSERT,
			DELETE_KEY = KEYCODE_DELETE,
			HOME = KEYCODE_HOME,
			END = KEYCODE_END,
			PAGE_UP = KEYCODE_PAGE_UP,
			PAGE_DOWN = KEYCODE_PAGE_DOWN,

			CAPS_LOCK = KEYCODE_CAPS_LOCK,
			SELECT = KEYCODE_SELECT,
			PRINT = KEYCODE_PRINT,
			EXECUTE = KEYCODE_EXECUTE,
			HELP = KEYCODE_HELP,
			PRINT_SCREEN = KEYCODE_HELP,
			PAUSE = KEYCODE_PAUSE,

			F1 = KEYCODE_F1,
			F2 = KEYCODE_F2,
			F3 = KEYCODE_F3,
			F4 = KEYCODE_F4,
			F5 = KEYCODE_F5,
			F6 = KEYCODE_F6,
			F7 = KEYCODE_F7,
			F8 = KEYCODE_F8,
			F9 = KEYCODE_F9,
			F10 = KEYCODE_F10,
			F11 = KEYCODE_F11,
			F12 = KEYCODE_F12,
			F13 = KEYCODE_F13,
			F14 = KEYCODE_F14,
			F15 = KEYCODE_F15,
			F16 = KEYCODE_F16,
			F17 = KEYCODE_F17,
			F18 = KEYCODE_F18,
			F19 = KEYCODE_F19,
			F20 = KEYCODE_F20,
			F21 = KEYCODE_F21,
			F22 = KEYCODE_F22,
			F23 = KEYCODE_F23,
			F24 = KEYCODE_F24,
			F25 = KEYCODE_F25,


			SHIFT = KEYCODE_SHIFT,
			LEFT_SHIFT = KEYCODE_LEFT_SHIFT,
			RIGHT_SHIFT = KEYCODE_RIGHT_SHIFT,

			CONTROL = KEYCODE_CONTROL,
			LEFT_CONTROL = KEYCODE_LEFT_CONTROL,
			RIGHT_CONTROL = KEYCODE_RIGHT_CONTROL,

			ALT = KEYCODE_ALT,
			LEFT_ALT = KEYCODE_LEFT_ALT,
			RIGHT_ALT = KEYCODE_RIGHT_ALT,

			LEFT_SUPER = KEYCODE_LEFT_SUPER,
			RIGHT_SUPER = KEYCODE_RIGHT_SUPER,

			MENU = KEYCODE_MENU,
			LAST = KEYCODE_LAST,
			SIZE
		};

		KeyCode() : code(0) {}
		KeyCode(uint32 code) : code(code) {}

		operator uint32() const { return code; }

		uint32 code;
	};


	class MouseCode
	{
	public:
		enum
		{
			LEFT_MOUSE = MOUSE_LBUTTON,
			RIGHT_MOUSE = MOUSE_RBUTTON,
			MIDDLE_MOUSE = MOUSE_MBUTTON,
			LAST = MIDDLE_MOUSE,
			SIZE
		};

		MouseCode() : code(0) {}
		MouseCode(uint32 code) : code(code) {}

		operator uint32() const { return code; }

		uint32 code;
	};

}
